### ISSUE TITLE
Linter showing a syntax error in a file which runs fine?

### ISSUE THREAD

**Issue by khpeek** [trezona-lecomte/SublimeLinter-contrib-sqlint#3]
I've posted a question about the linter on StackOverflow: https://stackoverflow.com/questions/52784179/sqlint-showing-a-syntax-error-yet-batch-file-is-run-correctly. It seems that for the SQL script

```SQL
CREATE TABLE shop (
    article INT(4) UNSIGNED ZEROFILL DEFAULT '0000' NOT NULL,
    dealer  CHAR(20)                 DEFAULT ''     NOT NULL,
    price   DOUBLE(16,2)             DEFAULT '0.00' NOT NULL,
    PRIMARY KEY(article, dealer));
INSERT INTO shop VALUES
    (1,'A',3.45),(1,'B',3.99),(2,'A',10.99),(3,'B',1.45),
    (3,'C',1.69),(3,'D',1.25),(4,'D',19.95);
```
It is showing a syntax error at the `INT(4)`, but I don't understand why as the syntax looks valid and runs correctly?

**Comment by trezona-lecomte** [comment]
Hi @khpeek, sorry that you've encountered this issue! Unfortunately this isn't an easy fix because the problem is that `sqlint` currently uses the PostgreSQL parser (as per [the sqlint readme](https://github.com/purcell/sqlint#about). 

Your snippet is valid MySQL, but not valid PostgreSQL. You can verify this quickly by running it through both parsers [here](https://rextester.com/l/mysql_online_compiler), notice that it fails with the same error you're getting when using PostgreSQL doesn't fail with this error when using MySQL.
